import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/Label";
import { EventPager } from "@/components/ui/Pagination";
import { ScrollArea } from "@/components/ui/ScrollArea";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/Select";
import { Separator } from "@/components/ui/Separator";
import { Td, Th, Tr } from "@/components/ui/Table";

import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [page, setPage] = useState(1);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen p-10 flex flex-col gap-5 justify-center items-center">
        {/* buttone example */}
        <Button>Submit</Button>

        {/* table example */}
        <div className="my-6 w-full overflow-y-auto">
          <table className="w-full">
            <thead>
              <Tr>
                <Th>King Treasury</Th>
                <Th>People happiness</Th>
              </Tr>
            </thead>
            <tbody>
              <Tr>
                <Td>Empty</Td>
                <Td>Overflowing</Td>
              </Tr>
              <Tr>
                <Td>Modest</Td>
                <Td>Satisfied</Td>
              </Tr>
              <tr className="m-0 border-t border-slate-200 p-0 even:bg-slate-100 dark:border-slate-600 dark:even:bg-slate-800">
                <Td>Full</Td>
                <Td>Ecstatic</Td>
              </tr>
            </tbody>
          </table>
        </div>

        {/* pagination example */}
        <EventPager
          count={20}
          page={page}
          onChange={(_, page) => setPage(page)}
        />

        {/* input example */}
        <div className="grid w-full max-w-sm items-center gap-1.5">
          <Label htmlFor="email">Email</Label>
          <Input type="email" id="email" placeholder="Email" />
        </div>

        {/* separator example */}
        <Separator />

        {/* select example */}
        <Select>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="Select a fruit" />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              <SelectLabel>Fruits</SelectLabel>
              <SelectItem value="apple">Apple</SelectItem>
              <SelectItem value="banana">Banana</SelectItem>
              <SelectItem value="blueberry">Blueberry</SelectItem>
              <SelectItem value="grapes">Grapes</SelectItem>
              <SelectItem value="pineapple">Pineapple</SelectItem>
            </SelectGroup>
            <SelectSeparator />
            <SelectGroup>
              <SelectLabel>Vegetables</SelectLabel>
              <SelectItem value="aubergine">Aubergine</SelectItem>
              <SelectItem value="broccoli">Broccoli</SelectItem>
              <SelectItem value="carrot" disabled>
                Carrot
              </SelectItem>
              <SelectItem value="courgette">Courgette</SelectItem>
              <SelectItem value="leek">Leek</SelectItem>
            </SelectGroup>
          </SelectContent>
        </Select>

        {/* scroll area example */}
        <ScrollArea className="h-[200px] w-[350px] rounded-md border p-4">
          Jokester began sneaking into the castle in the middle of the night and
          leaving jokes all over the place: under the king&apos;s pillow, in his
          soup, even in the royal toilet. The king was furious, but he
          couldn&apos;t seem to stop Jokester. And then, one day, the people of
          the kingdom discovered that the jokes left by Jokester were so funny
          that they couldn&apos;t help but laugh. And once they started
          laughing, they couldn&apos;t stop.
        </ScrollArea>
      </main>
    </>
  );
}
